.TH "code.settings" 3 "Thu Jul 25 2019" "Version 0.1" "schemaTool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code.settings
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBROOT\fP = 'http://local\-info\&.rothamsted\&.ac\&.uk/eRA/era2018\-new/'"
.br
.ti -1c
.RI "string \fBSTAGE\fP = 'd:/eRAstage2/'"
.br
.ti -1c
.RI "string \fBDEFAULT\fP = 'metadata/default/'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package settings.py
Created on 13 june 2019

@author: castells
@description: general settings of the web site
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for schemaTool from the source code\&.
