.TH "code.database.DocumentInfo" 3 "Wed Jul 10 2019" "Version 0.1" "schemaTool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code.database.DocumentInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBmdId\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for schemaTool from the source code\&.
