.TH "code.database.Person" 3 "Wed Jul 10 2019" "Version 0.1" "schemaTool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code.database.Person
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, row)"
.br
.ti -1c
.RI "def \fBformatAddress\fP (self)"
.br
.ti -1c
.RI "def \fBasCreatorJson\fP (self)"
.br
.ti -1c
.RI "def \fBasContributorJson\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfamilyName\fP"
.br
.ti -1c
.RI "\fBgivenName\fP"
.br
.ti -1c
.RI "\fBnameIdentifier\fP"
.br
.ti -1c
.RI "\fBnameIdentifierScheme\fP"
.br
.ti -1c
.RI "\fBschemeUri\fP"
.br
.ti -1c
.RI "\fBorganisationName\fP"
.br
.ti -1c
.RI "\fBstreet\fP"
.br
.ti -1c
.RI "\fBlocality\fP"
.br
.ti -1c
.RI "\fBregion\fP"
.br
.ti -1c
.RI "\fBcountry\fP"
.br
.ti -1c
.RI "\fBpostalCode\fP"
.br
.ti -1c
.RI "\fBfullname\fP"
.br
.ti -1c
.RI "\fBcontributorType\fP"
.br
.ti -1c
.RI "\fBnameIdentifiers\fP"
.br
.ti -1c
.RI "\fBaffiliations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for schemaTool from the source code\&.
