.TH "code.database" 3 "Wed Jul 10 2019" "Version 0.1" "schemaTool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code.database
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDocumentInfo\fP"
.br
.ti -1c
.RI "class \fBPerson\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconnect\fP ()"
.br
.ti -1c
.RI "def \fBgetCursor\fP ()"
.br
.ti -1c
.RI "def \fBgetDocumentMetadata\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareCreators\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareContributors\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareSubjects\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareDescriptions\fP (row)"
.br
.ti -1c
.RI "def \fBprepareDates\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareRelatedIdentifiers\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareSizes\fP (mdId)"
.br
.ti -1c
.RI "def \fBprepareFundingReferences\fP (mdId)"
.br
.ti -1c
.RI "def \fBprocess\fP (documentInfo)"
.br
.ti -1c
.RI "def \fBlogDoiMinted\fP (documentInfo)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Created on 9 Aug 2018

@author: ostlerr

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for schemaTool from the source code\&.
